version: '3'
services:
  tf_serving:
    image: bitnami/tensorflow-serving:2
    volumes:
      - ${PWD}/clothing-model:/bitnami/model-data/1
    ports:
      - 8500:8500
    environment:
      - TENSORFLOW_SERVING_MODEL_NAME=clothing-model
