version: '3'
services:
  tf_serving:
    build: 
      dockerfile: image-model.dockerfile
    environment:
      - TENSORFLOW_SERVING_MODEL_NAME=clothing-model
  gateway:
    build: 
      dockerfile: image-gateway.dockerfile
    platform: linux/amd64
    ports:
      - 80:80
    environment:
      - TF_SERVING_HOST=tf_serving
